#
#
#

version: "3.9"

services:
  #
  #   application
  #
  app:
    build:
      context: ./app
      target: development
    container_name: app
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    expose:
      - 5000
    restart: always
    volumes:
      - ./app:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - static:/usr/src/app/app/static

  #
  #   nginx
  #
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - app
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - static:/usr/src/app/app/static

  #
  #   postgres
  #
  postgres:
    container_name: postgres
    image: postgres:15-alpine3.16
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  #
  #   rabbitmq
  #
  rabbitmq:
    container_name: rabbitmq
    expose:
      - 5672
    env_file:
      - .env
    hostname: rabbitmq
    image: rabbitmq:3.11.2-alpine
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  #
  #   celery
  #
  celery:
    build:
      context: ./app
      target: development
    command: celery -A app.celery:app worker --loglevel=info
    container_name: celery
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app


#
#
#
volumes:
  node_modules:
  postgres:
  static:
  rabbitmq:
